#!/bin/sh

BANNER='
	  ____      _        ____
	 / ___|__ _| | _____| __ )  _____  __
	| |   / _` | |/ / _ \  _ \ / _ \ \/ /
	| |__| (_| |   <  __/ |_) | (_) >  <
	 \____\__,_|_|\_\___|____/ \___/_/\_\

'
echo "$BANNER";

## Ubuntu 14.04 upgrade notice
echo '';
if lsb_release -r | grep -q '16.04'; then
  echo 'already on 16.04' > /dev/null;
else
  echo '---------------------------------------------------------';
  echo 'WARNING:';
  echo 'You are using an outdated and unsupported cakebox version';
  echo 'and are strongly advised to perform the in-box upgrade by';
  echo 'executing the `/cakebox/bash/ubuntu-16.sh` command.';
  echo '---------------------------------------------------------';
fi
